public class ApplicationConstants{

    public static String ACCEPT_VERSION   = '1.0.x';
    public static String BACKDOOR         = 'backdoor';
    public static String HTTPPOST         = 'POST';
    public static String HTTPGET          = 'GET';

    //Json Tokens
    public static String CLIENT_SECRET    = 'secret';
    public static String CLIENT_ID        = 'id';
    public static String CLIENT_NAME      = 'name';
    public static String ACCESS_TOKEN     = 'access_token';
    public static String TOKEN_TYPE       = 'token_type';
    public static String LOCATION         = 'location';
    public static String SITE_ID 		  = 'id';
    public static String SITE_NAME 		  = 'name';
    
    
    
    //URL Endpoints
    public static String CLIENT_ENDPOINT  = '/clients';
    public static String OAUTH_TOKEN      = '/oauth/token';
    public static String QR_CODE          = '/sam/event-invites';
    public static String SITES 			  = '/sites';
}